import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import NavDesktop from "./components/nav-desktop";
import NavBarMobile from "./components/nav-mobile";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RetroFit Underfloor Heating",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div>
            <NavDesktop />
          </div>
          <div>
            <NavBarMobile />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
